# Generated by Django 2.1.7 on 2019-05-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190502_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
    ]
